channels:
  - apple
  - pytorch
dependencies:
  - pytorch::pytorch
  - torchvision
  - torchaudio
  - torchmetrics
  - lightning
  - scikit-learn
  - polars
  - pandas
  - matplotlib
  - seaborn
  - tqdm
  - black
  - notebook
  - tensorboard
  - optuna
  - optuna-integration
  - altair
  - keras
  - tensorflow
  - ipywidgets
  - pyarrow
